version: "3.7"
services:
  tb_server:
    image: ${DOCKER_REGISTRY}/tensorboard-server:latest
    ports:
      - "${TB_SERVER_PORT}:6006"
    volumes:
      - type: bind
        source: ${JOB_DATA}
        target: /archive
      - type: bind
        source: ${LOGDIR}
        target: /logs
    build: ./tensorboard_server
  tb_api:
    image: ${DOCKER_REGISTRY}/tensorboard-rest-api:latest
    ports:
      - "${TB_API_PORT}:5000"
    volumes:
      - type: bind
        source: ${JOB_DATA}
        target: /archive
      - type: bind
        source: ${LOGDIR}
        target: /logs
    deploy:
      resources:
        limits:
          memory: 300m
    environment: 
      - DEBUG
    build: ./tensorboard_rest_api
