version: "3.7"
services:
  tb_server:
    build: ./tensorboard_server
    image: ${DOCKER_REGISTRY}/tensorboard-server:latest
    ports:
      - "${TB_SERVER_PORT}:6006"
    volumes:
      - type: bind
        source: ${JOB_DATA}
        target: /archive
      - type: bind
        source: ${LOGDIR}
        target: /logs
  tb_api:
    build: ./tensorboard_api
    image: ${DOCKER_REGISTRY}/tensorboard-api:latest
    ports:
      - "${TB_API_PORT}:5000"
    volumes:
      - type: bind
        source: ${JOB_DATA}
        target: /archive
      - type: bind
        source: ${LOGDIR}
        target: /logs
    environment: 
      - DEBUG
